apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
  namespace: protectonce-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheck
  template:
    metadata:
      labels:
        app: healthcheck
    spec:
      containers:
        - name: healthcheck
          image: public.ecr.aws/protectonce-agentless/app-health-check-protectonce:latest
          imagePullPolicy: Always
          env:
            - name: PO_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: do-secret
                  key: po-app-name
            - name: PO_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: do-secret
                  key: po-clientid
            - name: PO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: do-secret
                  key: po-token
            - name: PO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: do-secret
                  key: po-endpoint
            - name: PROTECTONCE_LOG_LEVEL
              value: "verbose"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PO_APP_TYPE
              value: "agentless"
            - name: PO_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: PROTECTONCE_SCOPE
              value: "agentless.kubernetes"
            - name: STAGE
              value: app
      restartPolicy: Always







