apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: protectonce-agentless-hpa
  namespace: protectonce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: protectonce-agentless
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80