
apiVersion: v1
kind: Secret
metadata:
 name: do-secret
 namespace: protectonce-watcher
type: Opaque
data:
 po-app-name: bWVtZWQtYXBw
 po-clientid: SzJpZ2NjVWZWUWFrUm5KZDVqbWxsUmQ1YzNITA==
 po-token: SzJpZ2NjVWZWUWFrUm5KZDVqbWxsUmQ1YzNITExZbFExdVM5cXNuRFNpdGJkbklPNlROelRiTURIRTJxRnp4N0Nxd0QxZDU=
 po-endpoint: aHR0cHM6Ly9hcGkuYXBwLnByb3RlY3RvbmNlLmNvbQ==